server:
  port: 8090
  servlet:
    context-path: /nacos-user/
spring:
  application:
    name: nacos-user
  profiles:
    active: dev

  config:
#    import: optional:nacos:instead # 没有指定配置文件加载时
    import: optional:nacos:nacos-user-dev.yaml # 指定加载的配置
#    import: "optional:nacos:" # 自寻找
#    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension} # 动态匹配

  cloud:
    nacos:
#      discovery:
#        server-addr: ${spring.cloud.nacos.config.server-addr}
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP # 若存在，优先级：2

#        namespace: #加载指定命名空间中内容，优先级：1


