spring:
  cloud:
    gateway:
      routes:
        - id: order-rule
          uri: lb://nacos-order
          predicates:
            - Path=/api/order/**
        - id: product-rule
          uri: lb://nacos-product
          predicates:
            - Path=/api/product/**