server:
  port: 7878
spring:
  # 结合网关做断言分流
  cloud:
    gateway:
      routes:
        - id: nacos-user
          uri: http://localhost:8089
          predicates:
            - Path=/nacos-user/**
  application:
    name: gateway

